<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use modava\customer\models\query\CustomerStatusCallQuery;
use Yii;
use yii\db\ActiveRecord;

class CustomerStatusCallTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'customer_status_call';
    }

    public static function find()
    {
        return new CustomerStatusCallQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-status-call-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-status-call-get-status-call-dat-hen-' . $this->language,
            'redis-customer-status-call-get-all-status-call-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-status-call-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-status-call-get-status-call-dat-hen-' . $this->language,
            'redis-customer-status-call-get-all-status-call-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getById($id, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-call-get-by-id-' . $id . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['id' => $id, 'language' => $language])->published()->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getStatusCallDatHen($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-call-get-status-call-dat-hen-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->accepted()->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAllStatusCall($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-call-get-all-status-call-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
