<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use modava\customer\models\query\CustomerOriginQuery;
use Yii;
use yii\db\ActiveRecord;

class CustomerOriginTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'customer_origin';
    }

    public static function find()
    {
        return new CustomerOriginQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-origin-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-fanpage-get-fanpage-by-origin-' . $this->id . '-' . $this->language,
            'redis-customer-origin-get-all-origin-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-origin-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-fanpage-get-fanpage-by-origin-' . $this->id . '-' . $this->language,
            'redis-customer-origin-get-all-origin-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getAgencyHasMany()
    {
        return $this->hasMany(CustomerAgencyTable::class, ['id' => 'agency_id'])
            ->viaTable('customer_agency_origin_hasmany', ['origin_id' => 'id']);
    }

    public static function getOriginByAgency($agency, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-origin-get-origin-by-agency-' . $agency . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->joinWith(['agencyHasMany'])->where(['customer_agency_origin_hasmany.agency_id' => $agency, self::tableName() . '.language' => $language])->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getById($id = null, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-origin-get-by-id-' . $id . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['id' => $id])->published()->andWhere(['language' => $language])->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAllOrigin($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-origin-get-all-origin-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
