<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use modava\customer\models\query\CustomerFanpageQuery;
use Yii;
use yii\db\ActiveRecord;

class CustomerFanpageTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'customer_fanpage';
    }

    public static function find()
    {
        return new CustomerFanpageQuery(get_called_class());
    }

    public function getOriginHasOne()
    {
        return $this->hasOne(CustomerOriginTable::class, ['id' => 'origin_id']);
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-fanpage-get-by-id-' . $this->id
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-fanpage-get-by-id-' . $this->id
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getById($id, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-fanpage-get-by-id-' . $id;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['id' => $id, 'language' => $language])->published()->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getFanpageByOrigin($origin, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-fanpage-get-fanpage-by-origin-' . $origin . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['origin_id' => $origin, 'language' => $language])->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
