<?php

namespace modava\customer\models\table;

use modava\customer\models\query\CustomerAgencyQuery;
use Yii;

class CustomerAgencyTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;

    public static function tableName()
    {
        return 'customer_agency';
    }

    public static function find()
    {
        return new CustomerAgencyQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-agency-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-agency-get-all-agency-' . $this->language,
            'redis-customer-origin-get-origin-by-agency-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-agency-get-by-id-' . $this->id . '-' . $this->language,
            'redis-customer-agency-get-all-agency-' . $this->language,
            'redis-customer-origin-get-origin-by-agency-' . $this->id . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getOriginHasMany()
    {
        return $this->hasMany(CustomerOriginTable::class, ['id' => 'origin_id'])
            ->viaTable('customer_agency_origin_hasmany', ['agency_id' => 'id']);
    }

    public static function getAllAgency($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-agency-get-all-agency-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getById($id = null, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-agency-get-by-id-' . $id . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['id' => $id, 'language' => $language])->published()->one();
            $cache->set($key, $data);
        }
        return $data;
    }
}
