<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use modava\customer\models\query\CustomerStatusFailQuery;
use Yii;
use yii\db\ActiveRecord;

class CustomerStatusFailTable extends \yii\db\ActiveRecord
{
    const STATUS_DISABLED = 0;
    const STATUS_PUBLISHED = 1;
    const TYPE_CALL_FAIL = 0;
    const TYPE_DONG_Y_FAIL = 1;
    const TYPE = [
        self::TYPE_CALL_FAIL => 'Lý do fail lịch',
        self::TYPE_DONG_Y_FAIL => 'Lý do chốt fail'
    ];

    public static function tableName()
    {
        return 'customer_status_fail';
    }

    public static function find()
    {
        return new CustomerStatusFailQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-status-fail-get-all-status-call-fail-' . $this->language,
            'redis-customer-status-fail-get-all-status-dong-y-fail-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-customer-status-fail-get-all-status-call-fail-' . $this->language,
            'redis-customer-status-fail-get-all-status-dong-y-fail-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getById($id, $language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-fail-get-by-id-' . $id . '-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where([self::tableName() . '.id' => $id, self::tableName() . '.language' => $language])->published()->one();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAllStatusCallFail($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-fail-get-all-status-call-fail-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->typeCall()->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getAllStatusDongYFail($language = null)
    {
        $language = $language ?: Yii::$app->language;
        $cache = Yii::$app->cache;
        $key = 'redis-customer-status-fail-get-all-status-dong-y-fail-' . $language;
        $data = $cache->get($key);
        if ($data == false) {
            $data = self::find()->where(['language' => $language])->typeDongY()->published()->all();
            $cache->set($key, $data);
        }
        return $data;
    }
}
