<?php

namespace modava\customer\models\table;

use cheatsheet\Time;
use Yii;
use yii\db\ActiveRecord;

class CustomerTreatmentScheduleTable extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'customer_treatment_schedule';
    }

    public function getOrderHasOne()
    {
        return $this->hasOne(CustomerOrderTable::class, ['id' => 'order_id']);
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
