<?php
namespace modava\customer\components;

use backend\components\MyController;

class MyCustomerController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
