<?php

namespace modava\customer\models;

use common\helpers\MyHelper;
use common\models\User;
use cornernote\linkall\LinkAllBehavior;
use modava\customer\CustomerModule;
use modava\customer\models\table\CustomerAgencyTable;
use modava\customer\models\table\CustomerOriginTable;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\SluggableBehavior;
use yii\db\ActiveRecord;
use Yii;

/**
* This is the model class for table "customer_origin".
*
    * @property int $id
    * @property string $name
    * @property string $description
    * @property int $status
    * @property string $language Language
    * @property int $created_at
    * @property int $updated_at
    * @property int $created_by
    * @property int $updated_by
    *
            * @property CustomerAgencyOriginHasmany[] $customerAgencyOriginHasmanies
            * @property CustomerAgency[] $agencies
            * @property User $createdBy
            * @property User $updatedBy
    */
class CustomerOrigin extends CustomerOriginTable
{
    public $toastr_key = 'customer-origin';
    public $agencies;
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                [
                    'class' => BlameableBehavior::class,
                    'createdByAttribute' => 'created_by',
                    'updatedByAttribute' => 'updated_by',
                ],
                'timestamp' => [
                    'class' => 'yii\behaviors\TimestampBehavior',
                    'preserveNonEmptyValues' => true,
                    'attributes' => [
                        ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                        ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                    ],
                ],
                LinkAllBehavior::class
            ]
        );
    }

    /**
    * {@inheritdoc}
    */
    public function rules()
    {
        return [
			[['name'], 'required'],
			[['description', 'language'], 'string'],
			[['status', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
			[['name'], 'string', 'max' => 255],
			[['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['created_by' => 'id']],
			[['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['updated_by' => 'id']],
            [['agencies'], 'safe'],
		];
    }

    /**
    * {@inheritdoc}
    */
    public function attributeLabels()
    {
        return [
            'id' => CustomerModule::t('customer', 'ID'),
            'name' => CustomerModule::t('customer', 'Name'),
            'description' => CustomerModule::t('customer', 'Description'),
            'status' => CustomerModule::t('customer', 'Status'),
            'language' => CustomerModule::t('customer', 'Language'),
            'created_at' => CustomerModule::t('customer', 'Created At'),
            'updated_at' => CustomerModule::t('customer', 'Updated At'),
            'created_by' => CustomerModule::t('customer', 'Created By'),
            'updated_by' => CustomerModule::t('customer', 'Updated By'),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        $agencies = [];
        if (is_array($this->agencies)) {
            foreach ($this->agencies as $agency) {
                $get_agency = CustomerAgencyTable::getById($agency);
                if ($get_agency) {
                    $agencies[] = $get_agency;
                }
            }
        }
        $this->linkAll('agencyHasMany', $agencies);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
    * Gets query for [[User]].
    *
    * @return \yii\db\ActiveQuery
    */
    public function getUserCreated()
    {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }

    /**
    * Gets query for [[User]].
    *
    * @return \yii\db\ActiveQuery
    */
    public function getUserUpdated()
    {
        return $this->hasOne(User::class, ['id' => 'updated_by']);
    }
}
