<?php
namespace modava\customer\widgets;

class NavbarWidgets extends \yii\base\Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if(isset(CONSOLE_HOST) && CONSOLE_HOST == 1)
            return $this->render('navbarWidgets', []);
        else
            return '';
    }
}
